# Generated by Django 3.2.9 on 2022-07-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('items', '0004_transactiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionType',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_location', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='producer_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
