# Generated by Django 3.2.9 on 2022-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20220706_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='integer',
            field=models.BooleanField(default=True),
        ),
    ]
