# Generated by Django 3.2.13 on 2022-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_unit_integer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
