# Generated by Django 3.2.13 on 2022-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_unit_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='iso',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='integer',
            field=models.BooleanField(default=False),
        ),
    ]
