# Generated by Django 3.2.9 on 2022-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactionarchive_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionarchive',
            name='who',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
