# Generated by Django 3.2.9 on 2022-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactionarchive_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionarchive',
            name='transaction',
            field=models.CharField(choices=[['Input', 'Adding quantity of specific item on stock.'], ['Withdraw', 'Reduce quantity of specific item from stock.'], ['Total Scrap', 'Reduce quantity from stock to zero.'], ['Scrap', 'Reduce quantity of specific item from stock by scrapping.'], ['Return to Stock', 'Return withdrawn items to stock.']], max_length=32),
        ),
        migrations.AlterField(
            model_name='transactionarchive',
            name='who',
            field=models.CharField(default='Inter-Rex', max_length=64, null=True),
        ),
    ]
