# Generated by Django 3.2.9 on 2022-07-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20220704_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionarchive',
            name='transaction',
            field=models.CharField(max_length=32),
        ),
    ]
