# Generated by Django 3.2.9 on 2022-07-10 11:22

from django.db import migrations, models

def create_base_transactions(apps, schema_editor):
    file = open('base_transactions.json')
    data = json.load(file)
    transaction = apps.get_model('transactions', 'TransactionType')
    for trans in data:
        transaction.objects.create(**trans)

class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20220710_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionarchive',
            name='who',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
